services:
  app:
    build: .
    container_name: phoenix_xshare_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/phoenix-xshare
      - DOMAIN=http://localhost:3000
      - PORT=3000
      - ENCRYPTION=true
      - REGISTRATION_SECRET=
      - STORAGE_PROVIDER=local
    volumes:
      - uploads-data:/usr/src/app/src/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: phoenix_xshare_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  uploads-data:
  mongo-data:
